# -*- coding: utf-8 -*-
"""Copia de Práctica_1_Tabla_Hash_MyP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6R0hcgeX-NPok_RruVj8KLW9Iv7rhlr

# <font color=darkblue>**Facultad de Ciencias, UNAM**
# <font color=orange>**Laboratorio - Práctica 1 Tabla Hash**
# <font color=dark>**Modelado y Programación, semestre 2027-1**
# Prof. Karla Adriana Esquivel Guzmán
# Ayud. Ossiel Aguilar Espindola
> **López Juárez Aranza**

*Martes 01 de Septiembre del 2026*

#<font color=darkblue>**Objetivo**
Implementar desde cero una tabla hash capaz de almacenar pares

$$(key, value)$$

y que soporte las operaciones:

    insertar(key, value)
    buscar(key)
    eliminar(key)

La implementación deberá resolver correctamente las colisiones y deberá incluir pruebas básicas que demuestren el funcionamiento de la estructura.
Recordemos que una colisión ocurre cuando dos llaves distintas producen la misma posición:

$$k_1 \neq k_2 \quad \quad y \quad \quad h(k_1) = h(k_2)$$

#<font color=darkblue>**Verificación de la Solución**

*   <font color=darkblue>**Casos de prueba obligatorios**

**Prueba 1: Tabla Vacía**

Verificar:


```
NOT_FOUND
```
"""

buscar(tabla, 10, m)

mostrar_tabla(tabla)

"""**Prueba 2: inserción básica**"""

insertar(tabla, 18, "Ana", m)
insertar(tabla, 10, "Luis", m)
insertar(tabla, 23, "Elena", m)

"""Verificamos

```
buscar(18) -> Ana
buscar(10) -> Luis
buscar(23) -> Elena
```


"""

buscar(tabla, 10, m)

buscar(tabla, 23, m)

buscar(tabla, 18, m)

"""Comprobamos que estan en nuestra tabla:

"""

mostrar_tabla(tabla)

"""**Prueba 3: Colisiones**"""

insertar(tabla, 24, "Maria", m)
insertar(tabla, 31, "Carlos", m)

"""Comprobar


```
buscar(10) -> Luis
buscar(24) -> Maria
buscar(31) -> Carlos
```


"""

buscar(tabla, 10, m)

buscar(tabla, 24, m)

buscar(tabla, 31, m)

"""Comprobamos los datos en nuestra tabla:"""

mostrar_tabla(tabla)

"""**Prueba 4: Eliminación con colisión**"""

eliminar(tabla, 24, m)

"""Verificar


```
buscar(24) -> NOT_FOUND
buscar(10) -> Luis
buscar(31) -> Carlos
```


"""

buscar(tabla, 24, m)

buscar(tabla, 10, m)

buscar(tabla, 31, m)

"""Notemos que al eliminar un elemento de una cubeta no se eliminó
ni afectó los demás elementos almacenados en ella, así mostramos la tabla completa después de los cambios:
"""

mostrar_tabla(tabla)

"""**Prueba 5: Llave inexistente**"""

eliminar(tabla, 999, m)

"""Verificamos revisando que la tabla no se alteró:"""

mostrar_tabla(tabla)

"""**Prueba 6: Actualización de una llave existente**

Dado que ya teníamos la pareja de $(18, Ana)$, insertamos una nueva que tenga la misma key pero distinto value.



```
insertar(18, "Ana Maria")
```


"""

insertar(tabla, 18, "Ana Maria", m)

"""Buscamos la llave"""

buscar(tabla, 18, m)

"""Imprimimos la tabla completa:"""

mostrar_tabla(tabla)

"""Donde el valor de Ana, fue cambiado correctamente por el de Ana María. Manteniendo su llave y no duplicandola."""